### ISSUE TITLE
imzeromq does not work

### ISSUE THREAD

**Issue by takaomag** [aggregateknowledge/rsyslog-zeromq#1]
Hi,

I tried to test rsyslog-zeromq push/pull over tcp. But it does not work. Any hint ?

When I checked packets by tcpdump, I found,
- TCP connection between an omzeromq host and an imzeromq host  is surely establised.
- The omzeromq host surely transmits syslog packets to the imzeromq host.
- But it seems the imzeromq host does not work.
### Test situation
- omzeromq (transmitting) host: 192.168.0.10
- imzeromq (receiving) host: 192.168.0.11
- rsyslog 5.8.0 and 5.8.8
### rsyslog compiled option

> ./configure --enable-imzeromq --enable-omzeromq
### rsyslog.conf (omzeromq host)

```
$ModLoad immark
$ModLoad imuxsock
$ModLoad imklog
$ModLoad omzeromq

*.*                                                     :omzeromq:connect=tcp://192.168.0.11:514
&                                                       -/var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  -/var/log/cron
*.emerg                                                 *
uucp,news.crit                                          -/var/log/spooler
local7.*                                                /var/log/boot.log
```
### rsyslog.conf (imzeromq host)

```
$ModLoad immark
$ModLoad imuxsock
$ModLoad imklog
$ModLoad imzeromq.so

$Ruleset ZM
*.*                                                     *

$Ruleset RSYSLOG_DefaultRuleset
*.info;mail.none;authpriv.none;cron.none                -/var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  -/var/log/cron
*.emerg                                                 *
uucp,news.crit                                          -/var/log/spooler
local7.*                                                /var/log/boot.log

$InputZeroMQServerBindRuleset ZM
$InputZeroMQServerRun pattern=pull,bind=tcp://*:514
```

**Comment by aggregateknowledge** [comment]
I won't have time to test this until this weekend more than likely - in the middle of a datacenter retrofit at work.  I'll pass this info on to Ken (our main developer on the plugins) and see what he can find for you.  I've been using our output plugins and have not been using the inputs - so there very well could be a bug I'm not aware of.

Thanks for the feedback!

Brian

---

From: takaomag [reply@reply.github.com]
Sent: Tuesday, September 13, 2011 2:16 PM
To: Brian Knox
Subject: [rsyslog-zeromq] imzeromq does not work (#1)

Hi,

I tried to test rsyslog-zeromq push/pull over tcp. But it does not work. Any hint ?

When I checked packets by tcpdump, I found,
- TCP connection between an omzeromq host and an imzeromq host  is surely establised.
- The omzeromq host surely transmits syslog packets to the imzeromq host.
- But it seems the imzeromq host does not work.

### Test situation
- omzeromq (transmitting) host: 192.168.0.10
- imzeromq (receiving) host: 192.168.0.11
- rsyslog 5.8.0 and 5.8.8

### rsyslog compiled option

> ./configure --enable-imzeromq --enable-omzeromq

### rsyslog.conf (omzeromq host)

```
$ModLoad immark
$ModLoad imuxsock
$ModLoad imklog
$ModLoad omzeromq

*.*                                                     :omzeromq:connect=tcp://192.168.0.11:514
&                                                       -/var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  -/var/log/cron
*.emerg                                                 *
uucp,news.crit                                          -/var/log/spooler
local7.*                                                /var/log/boot.log
```

### rsyslog.conf (imzeromq host)

```
$ModLoad immark
$ModLoad imuxsock
$ModLoad imklog
$ModLoad imzeromq.so

$Ruleset ZM
*.*                                                     *

$Ruleset RSYSLOG_DefaultRuleset
*.info;mail.none;authpriv.none;cron.none                -/var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  -/var/log/cron
*.emerg                                                 *
uucp,news.crit                                          -/var/log/spooler
local7.*                                                /var/log/boot.log

$InputZeroMQServerBindRuleset ZM
$InputZeroMQServerRun pattern=pull,bind=tcp://*:514
```

## 

Reply to this email directly or view it on GitHub:
https://github.com/aggregateknowledge/rsyslog-zeromq/issues/1

**Comment by aggregateknowledge** [comment]
Taking a quick look at this - is this your full config?  It does not appear from the information you've sent that you're loading the input module -

---

$ModLoad immark
$ModLoad imuxsock
$ModLoad imklog

## $ModLoad omzeromq

Try adding a $ModLoad imzeromq if it is indeed missing.  If this doesn't fix it, let us know!  Thanks for the feedback.

Brian

---

From: takaomag [reply@reply.github.com]
Sent: Tuesday, September 13, 2011 2:16 PM
To: Brian Knox
Subject: [rsyslog-zeromq] imzeromq does not work (#1)

Hi,

I tried to test rsyslog-zeromq push/pull over tcp. But it does not work. Any hint ?

When I checked packets by tcpdump, I found,
- TCP connection between an omzeromq host and an imzeromq host  is surely establised.
- The omzeromq host surely transmits syslog packets to the imzeromq host.
- But it seems the imzeromq host does not work.

### Test situation
- omzeromq (transmitting) host: 192.168.0.10
- imzeromq (receiving) host: 192.168.0.11
- rsyslog 5.8.0 and 5.8.8

### rsyslog compiled option

> ./configure --enable-imzeromq --enable-omzeromq

### rsyslog.conf (omzeromq host)

```
$ModLoad immark
$ModLoad imuxsock
$ModLoad imklog
$ModLoad omzeromq

*.*                                                     :omzeromq:connect=tcp://192.168.0.11:514
&                                                       -/var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  -/var/log/cron
*.emerg                                                 *
uucp,news.crit                                          -/var/log/spooler
local7.*                                                /var/log/boot.log
```

### rsyslog.conf (imzeromq host)

```
$ModLoad immark
$ModLoad imuxsock
$ModLoad imklog
$ModLoad imzeromq.so

$Ruleset ZM
*.*                                                     *

$Ruleset RSYSLOG_DefaultRuleset
*.info;mail.none;authpriv.none;cron.none                -/var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  -/var/log/cron
*.emerg                                                 *
uucp,news.crit                                          -/var/log/spooler
local7.*                                                /var/log/boot.log

$InputZeroMQServerBindRuleset ZM
$InputZeroMQServerRun pattern=pull,bind=tcp://*:514
```

## 

Reply to this email directly or view it on GitHub:
https://github.com/aggregateknowledge/rsyslog-zeromq/issues/1

**Comment by takaomag** [comment]
Hi Brian,

Thank you for your very quick reply !

> Taking a quick look at this - is this your full config?  It does not appear from the information you've sent that you're loading the > input module -
> $ModLoad immark
> $ModLoad imuxsock
> $ModLoad imklog
> $ModLoad omzeromq

As I wrote in my original post, imzeromq (syslog receiving) host has "$ModLoad imzeromq.so". Another (syslog transmitting) host has "$Modload omzeromq".
And, at the rsyslog startup-time, rsyslogd does not claim any config parsing errors.

One more information, when I test normal tcp transport (imtcp) on same hosts and same tcp port, it does work well.

Thanks,
Takao Magoori

**Comment by aggregateknowledge** [comment]
Just as a heads up - rsyslog's config checking in my experience leaves quite a bit to be desired.  I've had cases where configs that had issues in them appeared to parse correctly.

Ken should be in the office on Thursday so if I don't get a chance to test this before then I'll hit him up and we'll make certain that we can get a working omzeromq -> imzeromq configuration verified.  I've only personally used omzeromq so far.

Ken - does the config require the ".so" at the end of the inputs?

Thank you for the feedback and the information!

Brian

**Comment by takaomag** [comment]
I'm sorry, there is one mistake.
-  tested rsyslog version
  
  rsyslog 5.8.0 and 5.8.8
       -> rsyslog 5.8.0 and 5.8.5

And, tested zeromq version is 2.1.9.

Thanks,
Takao Magoori

**Comment by aggregateknowledge** [comment]
Thanks for taking the time looking into this Ken!

Brian

**Comment by takaomag** [comment]
Hi ken,

Thank you so much for your help !
but I can not success yet.

> I've attached the full config files I used.

Config files are not attached. Could you please paste both files ?

> Have you disabled selinux and iptables on your machines?

Yes. And when I test normal tcp transport (imtcp) on same hosts and same tcp port, it does work well.

When the imzeromq (receiving) host receives a syslog message from the omzeromq (transmitting) host, the followin debug information is shown.

```
9696.343480373:7f8960d6d700: main Q: entry added, size now log 1, phys 1 entries
9696.343531666:7f8960d6d700: main Q: EnqueueMsg advised worker start
9696.343570178:7f8962d71700: wti 0x17378b0: worker awoke from idle processing
9696.343598201:7f8962d71700: we deleted 0 objects and enqueued 0 objects
9696.343616802:7f8962d71700: delete batch from store, new sizes: log 1, phys 1
9696.343636271:7f8962d71700: processBatch: batch of 1 elements must be processed
9696.343654640:7f8962d71700: Processing next rule
9696.343673439:7f8962d71700: testing filter, f_pmask 0
9696.343690954:7f8962d71700: Processing next action
9696.343710950:7f8962d71700: Called action(Batch), logging to builtin-file
9696.343731259:7f8962d71700: XXXXX:  tryDoAction 0x172de00, pnElem 1, nElem 1
9696.343750226:7f8962d71700: ruleset: get iRet 0 from rule.ProcessMsg()
9696.343767356:7f8962d71700: ruleset.ProcessMsg() returns 0
9696.343785259:7f8962d71700: regular consumer finished, iret=0, szlog 0 sz phys 1
9696.343806557:7f8962d71700: we deleted 1 objects and enqueued 0 objects
9696.343824027:7f8962d71700: delete batch from store, new sizes: log 0, phys 0
9696.343842041:7f8962d71700: regular consumer finished, iret=4, szlog 0 sz phys 0
9696.343859814:7f8962d71700: main Q:Reg/w0: worker IDLE, waiting for work.
```

Thanks.
